apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
<<<<<<< HEAD
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
      - port: 50000
        targetPort: 50000
=======
>>>>>>> d9ff7fdb4f22f22079eb991fb5103e5dfe90b12d
  selector:
    app: jenkins
