apiVersion: v1
kind: Pod
metadata:
  name: interpod-a
  labels:
    lab: interpod
spec:
  containers:
    - name: counter
      image: cjhouser/counter:1.0.0
      ports:
        - containerPort: 8080
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: interpod-b
  labels:
    lab: interpod
spec:
  containers:
    - name: shell
      image: alpine:3.14.2
      command: ["/bin/sh", "-c"]
      args:
        - sleep infinity;
  restartPolicy: Never
