apiVersion: v1
kind: Pod
metadata:
  name: counter-pod
spec:
  containers:
    - name: counter-container
      image: cjhouser/counter:v1
      ports:
        - name: counter-port
          containerPort: 8080
          protocol: TCP
  restartPolicy: Never