apiVersion: v1
kind: Pod
metadata:
  name: intrapod
spec:
  containers:
    - name: counter
      image: cjhouser/counter:1.0.0
      ports:
        - name: counter
          containerPort: 8080
          protocol: TCP
    - name: shell
      image: alpine:3.14.2
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            wget -q -O count http://localhost:8080/;
            sleep 10;
          done
  restartPolicy: Never