apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    lab: external-to-service
    app: counter
spec:
  containers:
    - name: counter
      image: cjhouser/counter:1.0.0
      ports:
        - containerPort: 8080
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata: 
  name: service 
  labels:
    lab: external-to-service
spec:
  selector:
    app: counter
  ports:
  - port: 8080
  type: LoadBalancer